
services:
  mariadb:
    build:
      context: ./requirements/mariadb/.
      dockerfile: Dockerfile
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    env_file:
      - .env.secrets
    networks:
      - inception-nw

  wordpress:
    build: 
      context: ./requirements/wordpress/.
      dockerfile: Dockerfile
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    restart: always
    env_file:
      - .env.secrets
    networks:
      - inception-nw

  nginx:
    build:
      context: ./requirements/nginx/.
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception-nw

networks:
  inception-nw:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/ddiniz-m/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ddiniz-m/data/wordpress
      o: bind

secrets:
  MYSQLROOTUSER:
    external: true
  MYSQLROOTPASSWORD:
    external: true
  MYSQLDATABASE:
    external: true
  MYSQLUSER:
    external: true
  MYSQLPASSWORD:
    external: true
  WPURL:
    external: true
  WPTITLE:
    external: true
  WPADMINUSER:
    external: true
  WPADMINPW:
    external: true
  WPADMINEMAIL:
    external: true
  WPUSER:
    external: true
  WPUSERPASS:
    external: true
  WPUSEREMAIL:
    external: true

# Services:
  # Defines different containers that make up application

  # Build:
  # Specifies where build should be searching for dockerfile and what is the name of the file. 
  # In this case, context and dockerfile is not needed beacuse dockerfile is called Dockerfile.
  # However, its good practice for more complex projects.

  # Environment:
  # Defines env variables to configure each container.

  # Volumes:
  # Maps a data directory or configuration file to the container.

  # Depends on X:
  # Ensures that X is stared before this container

  # Ports:
  # Exposes container on the port on local machine

# Volumes:
  # Defines names volumes that persist data between container restarts