
server 
{
	# SSL configuration | Define port that server will listen to
	listen 443 ssl;
	listen [::]:443 ssl;

	ssl_certificate /etc/nginx/tls/ddiniz-m.crt;
	ssl_certificate_key /etc/nginx/tls/ddiniz-m.key;

	ssl_protocols	TLSv1.3;

	root /var/www/html;

	error_log /var/log/nginx/error.log debug;

	# Add index.php to the list if you are using PHP
	index index.php index.html index.htm index.nginx-debian.html;

	server_name ddiniz-m.42.fr;

	# File Handling
	location / {
		# Attempt to serve request as file, then as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# PHP File Handling \ Passing PHP scripts to FastCGI server
	location ~ \.php$ {

		fastcgi_pass wordpress:9000;

		include fastcgi_params;

		fastcgi_index index.php;

		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}