
server 
{
	# SSL configuration; Define port that server will listen to. Listen for https connections on both IPv4 and IPv6 respectively;
	listen 443 ssl;
	listen [::]:443 ssl;

	#
	ssl_certificate /etc/nginx/tls/ddiniz-m.crt;
	ssl_certificate_key /etc/nginx/tls/ddiniz-m.key;

	#Supported protocols for SSL connections.
	ssl_protocols	TLSv1.3;

	root /var/www/html;

	# Defined which files Nginx will look for
	index index.php index.html index.htm index.nginx-debian.html;

	server_name ddiniz-m.42.fr;

	# File Handling
	location / {
		# Attempt to serve request as file, then as directory, then fall back to displaying a 404.
		try_files $uri $uri/ =404;
	}

	# .PHP File Handling
	location ~ \.php$ {

		#Where Nginx should send PHP requests
		fastcgi_pass wordpress:9000;

		#Includes parameter file to pass information to FastCGI server
		include fastcgi_params;
	
		#Sets a new parameter (SCRIPT_FILENAME). In this case if script name is index.php, SCRIPT_FILENAME becomes /var/www/html/index.html
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}